    let hornBrandsList: [String] = [
        "Accent",
        "Adams",
        "Alexander",
        "Allora",
        "Amati",
        "Ammoon",
        "Amrein",
        "Andalucia",
        "Antigua",
        "Apelila",
        "AR Resonance",
        "Aubertin",
        "Austin Winds",
        "Austin Custom Brass",
        "B&S",
        "B.A.C.",
        "Bach",
        "Baumann",
        "Beck",
        "Benchmark",
        "Benge",
        "Berkeley",
        "Bernd Schramm",
        "Besson (English)",
        "Besson (French)",
        "Best Brass",
        "Blackburn",
        "Blessing",
        "Bohland & Fuchs",
        "Boosey & Hawkes",
        "Büchel",
        "Buescher",
        "Bundy",
        "Burbank",
        "Calicchio",
        "Callet",
        "Cannonball",
        "CarolBrass",
        "Cecilio",
        "C.G. Conn",
        "Chatman Brass",
        "Conductor",
        "Conn",
        "Conn-Selmer",
        "Couesnon",
        "Courtois",
        "DaCarbo",
        "Del Quadro",
        "Dillon",
        "Divitt",
        "Don Miles",
        "Dotzauer",
        "Dowids",
        "Durand",
        "E.A. Couturier",
        "Eastar",
        "Eastman",
        "Eastrock",
        "Eclipse",
        "Edwards",
        "E.F. Durand",
        "Egger Galileo",
        "E.G. Wright",
        "Elephant",
        "Endres",
        "Etude",
        "Fides",
        "First Act",
        "Flip Oakes",
        "Fohqudill",
        "Galileo",
        "GalileoDolce",
        "Geneva",
        "Getzen",
        "Giardinelli",
        "Graves",
        "G&P",
        "Haag",
        "Haagston-Brassego",
        "Hackl",
        "Harrelson",
        "Harry B Jay",
        "Hawkes & Son",
        "Hawk",
        "Heimer",
        "Higham",
        "HN White",
        "Holton",
        "Hüttl",
        "I.K. Gottfried",
        "Inderbinen",
        "Jaeger",
        "Jean Baptiste",
        "Jean Paul",
        "Jenkins",
        "Jerome Wiss",
        "Jestaedt",
        "Jinyin Jinbao Xinghai",
        "John Packer",
        "J. Landress",
        "J. Scherzer",
        "Jupiter",
        "Kaizer",
        "Kanstul",
        "Keefer",
        "King",
        "Klangwerkstatt-Bohme",
        "Kühnl & Hoyer",
        "Lade",
        "Lark",
        "Larson Brasswerks",
        "Laskey-Pinc",
        "Lawler",
        "LeBlanc",
        "Lechner",
        "Leningrad",
        "Lidl",
        "LJ Hutchen",
        "Lotus",
        "Lyon & Healy",
        "Mack Brass",
        "Mahillon",
        "Manchester Brass",
        "Mandala",
        "Marcinkiewicz",
        "Martin",
        "Max",
        "Mazzio",
        "Mendini",
        "Merano",
        "MG Trumpets",
        "Monette",
        "Monke",
        "Navajo",
        "NYTC",
        "Odyssey",
        "Olds",
        "Osmun Music",
        "Pan American",
        "Peter Oberrauch",
        "Phaeton",
        "Phoenix",
        "P. Mauriat",
        "Possegger",
        "Powell",
        "pTrumpet",
        "Puje",
        "Raw Brass",
        "Reynolds",
        "Ricco Kühn",
        "Robinson Brass",
        "Romeo Adaci",
        "Rossetti",
        "Roy Benson",
        "Rudy Muck",
        "Schagerl",
        "Scherzer",
        "Schilke",
        "Schiller",
        "Schlub",
        "Scodwell",
        "Selmer",
        "S.E. Shires",
        "Severinsen-Akright",
        "Silvani & Smith",
        "Simba",
        "Smith-Watkins",
        "Sonare",
        "Spada",
        "Spencer",
        "Spiri",
        "Stagg",
        "Steinhoff",
        "Steinmeyer",
        "Stomvi",
        "Suzuki",
        "Taylor",
        "Temby",
        "Tempest",
        "Thein",
        "Thomann",
        "Trevor James",
        "Tristar",
        "Tromba",
        "Van Laar",
        "Verve",
        "V.F. Červeny",
        "Votruba",
        "Warburton",
        "Weber",
        "Wedgwood",
        "Weimann",
        "Weril",
        "Wessex",
        "Wohlrab",
        "Worischek",
        "Yamaha",
        "York",
        "York & Sons",
        "ZeuS",
        "Zirnbauer"
    ]
